// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATHIEd4D5cSAiSsfWKWEW-7iHySs0ZtIA',
    appId: '1:1061587763427:web:665c9aec4c40c5f3b4c5d6',
    messagingSenderId: '1061587763427',
    projectId: 'expense-tracker-86b64',
    authDomain: 'expense-tracker-86b64.firebaseapp.com',
    storageBucket: 'expense-tracker-86b64.appspot.com',
    measurementId: 'G-KD0R119GE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAsMUOOXA02zY4UT43cPRtEEpKdtC9aOo',
    appId: '1:1061587763427:android:a2a7159de92ac113b4c5d6',
    messagingSenderId: '1061587763427',
    projectId: 'expense-tracker-86b64',
    storageBucket: 'expense-tracker-86b64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByGOTbMGc2VdehIJq4Qocc_DqSpVMy7fs',
    appId: '1:1061587763427:ios:637f264759ae38beb4c5d6',
    messagingSenderId: '1061587763427',
    projectId: 'expense-tracker-86b64',
    storageBucket: 'expense-tracker-86b64.appspot.com',
    iosClientId: '1061587763427-8d5j69rpclvk5lm8kdelm37qilerg3gs.apps.googleusercontent.com',
    iosBundleId: 'com.savingoals.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByGOTbMGc2VdehIJq4Qocc_DqSpVMy7fs',
    appId: '1:1061587763427:ios:637f264759ae38beb4c5d6',
    messagingSenderId: '1061587763427',
    projectId: 'expense-tracker-86b64',
    storageBucket: 'expense-tracker-86b64.appspot.com',
    iosClientId: '1061587763427-8d5j69rpclvk5lm8kdelm37qilerg3gs.apps.googleusercontent.com',
    iosBundleId: 'com.savingoals.expensetracker',
  );
}
